# bring up the Dockerfile in a container called microdot
services:
  microdot:
    image: stevecooperorg/microdot:latest
    ports:
      - "7777:7777"
    volumes:
      # mount the user's home directory to /files in the container
      - ~/microdot:/files
      - ~/.microdot_history:/root/.microdot_history
    tty: true