services:
  # run the microdot container with the user's microdot files
  microdot:
    image: stevecooperorg/microdot:latest
    volumes:
      # mount the user's microdot files in their home directory to /files in the container
      - ~/microdot:/files
      # mount the user's microdot history file for history completion
      - ~/.microdot_history:/root/.microdot_history
    tty: true
  webserver:
    image: stevecooperorg/live-server:latest
    ports:
      - "7777:8080"
    volumes:
      - ~/microdot:/files
    depends_on:
      - microdot
  ngrok:
    image: ngrok/ngrok:latest
    volumes:
      - ~/microdot:/files:ro
    command: "http webserver:8080 --domain=${NGROK_DOMAIN}"
    profiles:
      - public
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_DOMAIN=${NGROK_DOMAIN}